config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get  "users/login"
  get  "pages/about_us"
  get  "pages/test"
  
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
    
    def test 
    end

    def about_us 
    end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def login
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <body class="homepage is-preload">
		<div id="page-wrapper">
		<!-- Header -->
		  <div id="header">		
			<!-- Nav -->
			  <nav id="nav">
					<ul>
						<li>
               <%= link_to "Home", root_path %>
            </li>
            <li>
               <%= link_to "Test", pages_test_path %>
            </li>
            <li>
               <%= link_to "Login", users_login_path %>
            </li>		
            <li>
               <%= link_to "About us", pages_about_us_path %>
            </li>					
   
					  <li>
              <a href="no-sidebar.html">No Sidebar</a>
            </li>
					</ul>
				</nav>
			</div>
    </div>
    
    <%= yield %>
    <!-- Footer -->
		<div id="footer">
			<div class="container">
          <div class="row">
          </div>
					<!-- Copyright -->
					<div class="copyright">
						<ul class="menu">
								<li>&copy; Untitled. All rights reserved.</li>
                <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
						</ul>
					</div>
			</div>
    </div>

  </body>
</html>

app/views/pages/about_us.html.erb
<h1>About us</>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

app/views/pages/index.html.erb
<h1> Rails es genial!</>
<br/>
<br/>


<p>
Commodo id natoque malesuada sollicitudin elit suscipit. Curae suspendisse mauris posuere accumsan massa
posuere lacus convallis tellus interdum. Amet nullam fringilla nibh nulla convallis ut venenatis purus
sit arcu sociis. Nunc fermentum adipiscing tempor cursus nascetur adipiscing adipiscing. Primis aliquam
mus lacinia lobortis phasellus suscipit. Fermentum lobortis non tristique ante proin sociis accumsan
lobortis. Auctor etiam porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum
consequat integer interdum integer purus sapien. Nibh eleifend nulla nascetur pharetra commodo mi augue
interdum tellus. Ornare cursus augue feugiat sodales velit lorem. Semper elementum ullamcorper lacinia
natoque aenean scelerisque.
</p>	
<br/>

app/views/pages/test.html.erb
<h1> Test</>
<br/>
<br/>
<br/>

<%= image_tag("helios.jpg")%>

app/views/users/login.html.erb
<h1>Login</>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>